import { databasePath } from "../settings.json"
import { Database } from "../src/backend/database/Database"
import { databaseObjectEqual } from "../src/utilities"
import * as path from "node:path"
import * as fs from "node:fs"

import { readPtCardList } from "../src/backend/ptCardOperations"
import { ptCardList } from '../json/csvColumns.json'
import { CsvRecord } from '../src/backend/types'
import { ptCardListLoadScript } from "../src/backend/database/sqliteScripts"
import { processPtCardList } from "../src/backend/ptCardOperations"

beforeAll(async () => {
    fs.copyFileSync('.\\sqlite\\test.db','.\\test\\test.db');
});
  
afterAll(() => {
    fs.unlink('.\\test\\test.db', () => {});
});

test('tests that jest with typescript works', () => {
    expect([1,2,3].reduce((acc, curr) => acc + curr, 0)).toBe(6);
})    

test('Read a card out of pt_card_list', async () => {

    const desiredData = {
        "Card Title": "MLB 2024 Live RP Guillermo Zuniga LAA",
        "Card ID": 64889,
        "Card Value": 40,
        "Card Type": 1,
        "Card Sub Type": 0,
        "Year": 2024,
        "Peak": "N",
        "Team": "Los Angeles Angels",
        "LastName": "Zuniga",
        "FirstName": "Guillermo",
        "NickName": "",
        "UniformNumber": 60,
        "DayOB": 10,
        "MonthOB": 10,
        "YearOB": 1998,
        "Bats": 1,
        "Throws": 1,
        "Position": 1,
        "Pitcher Role": 12,
        "Contact": 12,
        "Gap": 15,
        "Power": 3,
        "Eye": 11,
        "Avoid Ks": 15,
        "BABIP": 14,
        "Contact vL": 12,
        "Gap vL": 15,
        "Power vL": 3,
        "Eye vL": 11,
        "Avoid K vL": 15,
        "BABIP vL": 14,
        "Contact vR": 12,
        "Gap vR": 15,
        "Power vR": 3,
        "Eye vR": 11,
        "Avoid K vR": 15,
        "BABIP vR": 14,
        "GB Hitter Type": 0,
        "FB Hitter Type": 0,
        "BattedBallType": 0,
        "Speed": 14,
        "Steal Rate": 12,
        "Stealing": 6,
        "Baserunning": 24,
        "Sac bunt": 52,
        "Bunt for hit": 33,
        "Stuff": 67,
        "Movement": 65,
        "Control": 58,
        "pHR": 50,
        "pBABIP": 89,
        "Stuff vL": 62,
        "Movement vL": 58,
        "Control vL": 57,
        "pHR vL": 44,
        "pBABIP vL": 74,
        "Stuff vR": 71,
        "Movement vR": 71,
        "Control vR": 59,
        "pHR vR": 56,
        "pBABIP vR": 101,
        "Fastball": 43,
        "Slider": 43,
        "Curveball": 0,
        "Changeup": 37,
        "Cutter": 0,
        "Sinker": 0,
        "Splitter": 0,
        "Forkball": 0,
        "Screwball": 0,
        "Circlechange": 0,
        "Knucklecurve": 0,
        "Knuckleball": 0,
        "Stamina": 18,
        "Hold": 52,
        "GB": 4,
        "Velocity": "98-100",
        "Arm Slot": 2,
        "Height": 196,
        "Infield Range": 30,
        "Infield Error": 50,
        "Infield Arm": 33,
        "DP": 22,
        "CatcherAbil": 1,
        "CatcherFrame": 1,
        "Catcher Arm": 1,
        "OF Range": 1,
        "OF Error": 1,
        "OF Arm": 1,
        "Pos Rating P": 83,
        "Pos Rating C": 0,
        "Pos Rating 1B": 0,
        "Pos Rating 2B": 0,
        "Pos Rating 3B": 0,
        "Pos Rating SS": 0,
        "Pos Rating LF": 0,
        "Pos Rating CF": 0,
        "Pos Rating RF": 0,
        "LearnC": 0,
        "Learn1B": 1,
        "Learn2B": 1,
        "Learn3B": 1,
        "LearnSS": 0,
        "LearnLF": 0,
        "LearnCF": 0,
        "LearnRF": 0,
        "era": 8,
        "tier": 0,
        "MissionValue": 1,
        "limit": 0,
        "owned": 2,
        "brefid": "zuniga000gui",
        "Buy Order High": 0,
        "Sell Order Low": 20,
        "Last 10 Price": 21,
        "Buy Order High(CC)": 0,
        "Sell Order Low(CC)": 0,
        "Last 10 Price(CC)": 0,
        "date": "2024-04-17"
    }      

    const cards = await readPtCardList(".\\test\\data\\1_card_pt_card_list.csv", ptCardList)

    expect(cards.length).toBe(1);

    const loadedCard = cards[0];

    expect(databaseObjectEqual(loadedCard,desiredData)).toBeTruthy();

})

test('Populate PtCards table with record', async () => {

    const liveCard = {
        "Card Title": "MLB 2024 Live RP Guillermo Zuniga LAA",
        "Card ID": 64889,
        "Card Value": 40,
        "Card Type": 1,
        "Card Sub Type": 0,
        "Year": 2024,
        "Peak": "N",
        "Team": "Los Angeles Angels",
        "LastName": "Zuniga",
        "FirstName": "Guillermo",
        "NickName": "",
        "UniformNumber": 60,
        "DayOB": 10,
        "MonthOB": 10,
        "YearOB": 1998,
        "Bats": 1,
        "Throws": 1,
        "Position": 1,
        "Pitcher Role": 12,
        "Contact": 12,
        "Gap": 15,
        "Power": 3,
        "Eye": 11,
        "Avoid Ks": 15,
        "BABIP": 14,
        "Contact vL": 12,
        "Gap vL": 15,
        "Power vL": 3,
        "Eye vL": 11,
        "Avoid K vL": 15,
        "BABIP vL": 14,
        "Contact vR": 12,
        "Gap vR": 15,
        "Power vR": 3,
        "Eye vR": 11,
        "Avoid K vR": 15,
        "BABIP vR": 14,
        "GB Hitter Type": 0,
        "FB Hitter Type": 0,
        "BattedBallType": 0,
        "Speed": 14,
        "Steal Rate": 12,
        "Stealing": 6,
        "Baserunning": 24,
        "Sac bunt": 52,
        "Bunt for hit": 33,
        "Stuff": 67,
        "Movement": 65,
        "Control": 58,
        "pHR": 50,
        "pBABIP": 89,
        "Stuff vL": 62,
        "Movement vL": 58,
        "Control vL": 57,
        "pHR vL": 44,
        "pBABIP vL": 74,
        "Stuff vR": 71,
        "Movement vR": 71,
        "Control vR": 59,
        "pHR vR": 56,
        "pBABIP vR": 101,
        "Fastball": 43,
        "Slider": 43,
        "Curveball": 0,
        "Changeup": 37,
        "Cutter": 0,
        "Sinker": 0,
        "Splitter": 0,
        "Forkball": 0,
        "Screwball": 0,
        "Circlechange": 0,
        "Knucklecurve": 0,
        "Knuckleball": 0,
        "Stamina": 18,
        "Hold": 52,
        "GB": 4,
        "Velocity": "98-100",
        "Arm Slot": 2,
        "Height": 196,
        "Infield Range": 30,
        "Infield Error": 50,
        "Infield Arm": 33,
        "DP": 22,
        "CatcherAbil": 1,
        "CatcherFrame": 1,
        "Catcher Arm": 1,
        "OF Range": 1,
        "OF Error": 1,
        "OF Arm": 1,
        "Pos Rating P": 83,
        "Pos Rating C": 0,
        "Pos Rating 1B": 0,
        "Pos Rating 2B": 0,
        "Pos Rating 3B": 0,
        "Pos Rating SS": 0,
        "Pos Rating LF": 0,
        "Pos Rating CF": 0,
        "Pos Rating RF": 0,
        "LearnC": 0,
        "Learn1B": 1,
        "Learn2B": 1,
        "Learn3B": 1,
        "LearnSS": 0,
        "LearnLF": 0,
        "LearnCF": 0,
        "LearnRF": 0,
        "era": 8,
        "tier": 0,
        "MissionValue": 1,
        "limit": 0,
        "owned": 2,
        "brefid": "zuniga000gui",
        "Buy Order High": 0,
        "Sell Order Low": 20,
        "Last 10 Price": 21,
        "Buy Order High(CC)": 0,
        "Sell Order Low(CC)": 0,
        "Last 10 Price(CC)": 0,
        "date": "2024-04-17"
    } as CsvRecord

    const historicalCard = {
        "Card Title": "Mission Week 2 - Super Util 2B Ben Zobrist TB 2009",
        "Card ID": 65911,
        "Card Value": 102,
        "Card Type": 10,
        "Card Sub Type": 60,
        "Year": 2009,
        "Peak": "N",
        "Team": "Tampa Bay Rays",
        "LastName": "Ben",
        "FirstName": "Zobrist",
        "NickName": "",
        "UniformNumber": 60,
        "DayOB": 10,
        "MonthOB": 10,
        "YearOB": 1998,
        "Bats": 3,
        "Throws": 1,
        "Position": 4,
        "Pitcher Role": 12,
        "Contact": 12,
        "Gap": 15,
        "Power": 3,
        "Eye": 11,
        "Avoid Ks": 15,
        "BABIP": 14,
        "Contact vL": 12,
        "Gap vL": 15,
        "Power vL": 3,
        "Eye vL": 11,
        "Avoid K vL": 15,
        "BABIP vL": 14,
        "Contact vR": 12,
        "Gap vR": 15,
        "Power vR": 3,
        "Eye vR": 11,
        "Avoid K vR": 15,
        "BABIP vR": 14,
        "GB Hitter Type": 0,
        "FB Hitter Type": 0,
        "BattedBallType": 0,
        "Speed": 14,
        "Steal Rate": 12,
        "Stealing": 6,
        "Baserunning": 24,
        "Sac bunt": 52,
        "Bunt for hit": 33,
        "Stuff": 67,
        "Movement": 65,
        "Control": 58,
        "pHR": 50,
        "pBABIP": 89,
        "Stuff vL": 62,
        "Movement vL": 58,
        "Control vL": 57,
        "pHR vL": 44,
        "pBABIP vL": 74,
        "Stuff vR": 71,
        "Movement vR": 71,
        "Control vR": 59,
        "pHR vR": 56,
        "pBABIP vR": 101,
        "Fastball": 43,
        "Slider": 43,
        "Curveball": 0,
        "Changeup": 37,
        "Cutter": 0,
        "Sinker": 0,
        "Splitter": 0,
        "Forkball": 0,
        "Screwball": 0,
        "Circlechange": 0,
        "Knucklecurve": 0,
        "Knuckleball": 0,
        "Stamina": 18,
        "Hold": 52,
        "GB": 4,
        "Velocity": "98-100",
        "Arm Slot": 2,
        "Height": 196,
        "Infield Range": 30,
        "Infield Error": 50,
        "Infield Arm": 33,
        "DP": 22,
        "CatcherAbil": 1,
        "CatcherFrame": 1,
        "Catcher Arm": 1,
        "OF Range": 1,
        "OF Error": 1,
        "OF Arm": 1,
        "Pos Rating P": 83,
        "Pos Rating C": 0,
        "Pos Rating 1B": 0,
        "Pos Rating 2B": 0,
        "Pos Rating 3B": 0,
        "Pos Rating SS": 0,
        "Pos Rating LF": 0,
        "Pos Rating CF": 0,
        "Pos Rating RF": 0,
        "LearnC": 0,
        "Learn1B": 1,
        "Learn2B": 1,
        "Learn3B": 1,
        "LearnSS": 0,
        "LearnLF": 0,
        "LearnCF": 0,
        "LearnRF": 0,
        "era": 7,
        "tier": 5,
        "MissionValue": 200,
        "limit": 0,
        "owned": 0,
        "brefid": "zobris001ben",
        "Buy Order High": 92000,
        "Sell Order Low": 164999,
        "Last 10 Price": 169942,
        "Buy Order High(CC)": 0,
        "Sell Order Low(CC)": 0,
        "Last 10 Price(CC)": 0,
        "date": "2024-12-23"        
    }

    const expectedLiveCard = {
        "CardTitle": "MLB 2024 Live RP Guillermo Zuniga LAA",
        "CardID": 64889,
        "CardValue": 40,
    }

    const historicalLiveCard = {
        "CardTitle": "Mission Week 2 - Super Util 2B Ben Zobrist TB 2009",
        "CardID": 65911,
        "CardValue": 102,
    }

    const script = await ptCardListLoadScript([liveCard,historicalCard],ptCardList);
    const database = new Database(".\\test\\test.db");

    await database.execute(script);
    const liveCardRecord = await database.get(`select CardID,CardTitle,CardValue from PtCard where CardID = 64889`)
    const historicalCardRecord = await database.get(`select CardID,CardTitle,CardValue from PtCard where CardID = 65911`)
    
    expect(databaseObjectEqual(liveCardRecord,expectedLiveCard)).toBeTruthy();
    expect(databaseObjectEqual(historicalCardRecord,historicalLiveCard)).toBeTruthy();

})

// test('Run table load', async () => {
//     await processPtCardList();

//     const db = new Database(".\\test\\test.db");
//     const result = await db.get("SELECT COUNT(*) FROM Card");

//     console.log(result);

// })