import { databasePath } from "../settings.json"
import { Database } from "../src/backend/database/Database"
import { databaseObjectEqual } from "../src/utilities"
import * as path from "node:path"
import * as fs from "node:fs"

import { readPtCardList } from "../src/backend/ptCardOperations"
import { ptCardList } from '../json/csvColumns.json'
import { CsvRecord } from '../src/backend/types'
import { ptCardListLoadScript } from "../src/backend/database/sqliteScripts"
import { processPtCardList, getLiveUpdates, writeLiveUpdate,  } from "../src/backend/ptCardOperations"

const dir = 'E:\\ootp_data\\sqlite\\'

beforeAll(async () => {
    fs.copyFileSync(dir + 'pt.db',dir + 'test.db');
});
  
afterAll(() => {
    fs.unlink(dir + 'test.db', () => {});
});

test('Read a card out of pt_card_list', async () => {

    const desiredData = {
        "Card Title": "Snapshot RP George Zuverink BAL 1958",
        "Card ID": 70594,
        "Card Value": 69,
        "Card Type": 7,
        "Card Sub Type": 0,
        "Card Badge": "",
        "Card Series": "",
        "Year": 1958,
        "Peak": "N",
        "Team": "Baltimore Orioles",
        "Franchise": "BAL",
        "LastName": "Zuverink",
        "FirstName": "George",
        "NickName": "",
        "UniformNumber": 35,
        "DayOB": 20,
        "MonthOB": 8,
        "YearOB": 1924,
        "Bats": 1,
        "Throws": 1,
        "Position": 1,
        "Pitcher Role": 12,
        "Contact": 3,
        "Gap": 4,
        "Power": 2,
        "Eye": 2,
        "Avoid Ks": 1,
        "BABIP": 1,
        "Contact vL": 3,
        "Gap vL": 4,
        "Power vL": 2,
        "Eye vL": 3,
        "Avoid K vL": 1,
        "BABIP vL": 1,
        "Contact vR": 3,
        "Gap vR": 4,
        "Power vR": 2,
        "Eye vR": 2,
        "Avoid K vR": 1,
        "BABIP vR": 1,
        "GB Hitter Type": 0,
        "FB Hitter Type": 0,
        "BattedBallType": 0,
        "Speed": 6,
        "Steal Rate": 3,
        "Stealing": 6,
        "Baserunning": 8,
        "Sac bunt": 25,
        "Bunt for hit": 44,
        "Stuff": 36,
        "Movement": 94,
        "Control": 93,
        "pHR": 102,
        "pBABIP": 79,
        "Stuff vL": 32,
        "Movement vL": 73,
        "Control vL": 117,
        "pHR vL": 72,
        "pBABIP vL": 76,
        "Stuff vR": 38,
        "Movement vR": 121,
        "Control vR": 77,
        "pHR vR": 140,
        "pBABIP vR": 83,
        "Fastball": 33,
        "Slider": 0,
        "Curveball": 33,
        "Changeup": 0,
        "Cutter": 0,
        "Sinker": 46,
        "Splitter": 0,
        "Forkball": 0,
        "Screwball": 0,
        "Circlechange": 0,
        "Knucklecurve": 0,
        "Knuckleball": 0,
        "Stamina": 25,
        "Hold": 36,
        "GB": 2,
        "Velocity": "88-90",
        "Arm Slot": 3,
        "Height": 193,
        "Infield Range": 35,
        "Infield Error": 20,
        "Infield Arm": 26,
        "DP": 23,
        "CatcherAbil": 0,
        "CatcherFrame": 0,
        "Catcher Arm": 0,
        "OF Range": 1,
        "OF Error": 4,
        "OF Arm": 8,
        "Pos Rating P": 65,
        "Pos Rating C": 0,
        "Pos Rating 1B": 0,
        "Pos Rating 2B": 0,
        "Pos Rating 3B": 0,
        "Pos Rating SS": 0,
        "Pos Rating LF": 0,
        "Pos Rating CF": 0,
        "Pos Rating RF": 0,
        "LearnC": 0,
        "Learn1B": 0,
        "Learn2B": 0,
        "Learn3B": 0,
        "LearnSS": 0,
        "LearnLF": 0,
        "LearnCF": 0,
        "LearnRF": 0,
        "era": 2,
        "tier": 1,
        "MissionValue": 2,
        "limit": 0,
        "owned": 0,
        "brefid": "zuverge01",
        "Buy Order High": 39,
        "Sell Order Low": 149,
        "Last 10 Price": 150,
        "Last 10 Price(VAR)": 0,
        "date": "2025-03-14"        
    }

    const cards = await readPtCardList(".\\test\\data\\1_card_pt_card_list.csv", ptCardList)

    expect(cards.length).toBe(1);

    const loadedCard = cards[0];

    expect(databaseObjectEqual(loadedCard,desiredData)).toBeTruthy();

})

test('LiveUpdate CRUD', async () => {

    const databasePath = dir + "test.db";
    
    const liveUpdateID = await writeLiveUpdate(databasePath, {LiveUpdateID: null, EffectiveDate: '2025-04-01'});
    const liveUpdates1 = await getLiveUpdates(databasePath);
    
    expect(liveUpdates1.find((liveUpdate) => liveUpdate.LiveUpdateID === liveUpdateID)?.EffectiveDate).toBe('2025-04-01');

    await writeLiveUpdate(databasePath, {LiveUpdateID: liveUpdateID, EffectiveDate: '2025-04-15'});
    const liveUpdates2 = await getLiveUpdates(databasePath);

    expect(liveUpdates2.find((liveUpdate) => liveUpdate.LiveUpdateID === liveUpdateID)?.EffectiveDate).toBe('2025-04-15');

})

test('Populate PtCards table with record', async () => {

    const liveCard = {
        "Card Title": "MLB 2025 Live RF Jared Young NYM",
        "Card ID": 72325,
        "Card Value": 67,
        "Card Type": 1,
        "Card Sub Type": 0,
        "Card Badge": "",
        "Card Series": "",
        "Year": 2025,
        "Peak": "N",
        "Team": "New York Mets",
        "Franchise": "NYM",
        "LastName": "Young",
        "FirstName": "Jared",
        "NickName": "",
        "UniformNumber": 3,
        "DayOB": 9,
        "MonthOB": 7,
        "YearOB": 1995,
        "Bats": 2,
        "Throws": 1,
        "Position": 9,
        "Pitcher Role": 0,
        "Contact": 67,
        "Gap": 86,
        "Power": 77,
        "Eye": 85,
        "Avoid Ks": 66,
        "BABIP": 71,
        "Contact vL": 65,
        "Gap vL": 82,
        "Power vL":74,
        "Eye vL": 79,
        "Avoid K vL": 63,
        "BABIP vL": 70,
        "Contact vR": 69,
        "Gap vR": 87,
        "Power vR": 79,
        "Eye vR": 88,
        "Avoid K vR": 68,
        "BABIP vR": 72,
        "GB Hitter Type": 2,
        "FB Hitter Type": 2,
        "BattedBallType": 0,
        "Speed": 67,
        "Steal Rate": 31,
        "Stealing": 70,
        "Baserunning": 67,
        "Sac bunt": 64,
        "Bunt for hit": 33,
        "Stuff": 1,
        "Movement": 20,
        "Control": 1,
        "pHR": 1,
        "pBABIP": 60,
        "Stuff vL": 1,
        "Movement vL": 20,
        "Control vL": 1,
        "pHR vL": 1,
        "pBABIP vL": 59,
        "Stuff vR": 1,
        "Movement vR": 21,
        "Control vR": 1,
        "pHR vR": 1,
        "pBABIP vR": 62,
        "Fastball": 9,
        "Slider": 0,
        "Curveball": 0,
        "Changeup": 0,
        "Cutter": 0,
        "Sinker": 0,
        "Splitter": 0,
        "Forkball": 0,
        "Screwball": 0,
        "Circlechange": 0,
        "Knucklecurve": 0,
        "Knuckleball": 0,
        "Stamina": 1,
        "Hold": 0,
        "GB": 4,
        "Velocity": "80-83",
        "Arm Slot": 3,
        "Height": 185,
        "Infield Range": 44,
        "Infield Error": 55,
        "Infield Arm": 53,
        "DP": 48,
        "CatcherAbil": 1,
        "CatcherFrame": 1,
        "Catcher Arm": 4,
        "OF Range": 54,
        "OF Error": 60,
        "OF Arm": 51,
        "Pos Rating P": 0,
        "Pos Rating C": 0,
        "Pos Rating 1B": 13,
        "Pos Rating 2B": 0,
        "Pos Rating 3B": 0,
        "Pos Rating SS": 0,
        "Pos Rating LF": 12,
        "Pos Rating CF": 0,
        "Pos Rating RF": 50,
        "LearnC": 0,
        "Learn1B": 1,
        "Learn2B": 1,
        "Learn3B": 1,
        "LearnSS": 1,
        "LearnLF": 1,
        "LearnCF": 1,
        "LearnRF": 1,
        "era": 8,
        "tier": 1,
        "MissionValue": 2,
        "limit": 0,
        "owned": 0,
        "brefid": "youngja02",
        "Buy Order High": 60,
        "Sell Order Low": 195,
        "Last 10 Price": 115,
        "Last 10 Price(VAR)": 0,
        "date": "2025-03-15"
    } as CsvRecord

    const historicalCard = {
        "Card Title": "Snapshot RP George Zuverink BAL 1958",
        "Card ID": 70594,
        "Card Value": 69,
        "Card Type": 7,
        "Card Sub Type": 0,
        "Card Badge": "",
        "Card Series": "",
        "Year": 1958,
        "Peak": "N",
        "Team": "Baltimore Orioles",
        "Franchise": "BAL",
        "LastName": "Zuverink",
        "FirstName": "George,",
        "NickName": "",
        "UniformNumber": 35,
        "DayOB": 20,
        "MonthOB": 8,
        "YearOB": 1924,
        "Bats": 1,
        "Throws": 1,
        "Position": 1,
        "Pitcher Role": 12,
        "Contact": 3,
        "Gap": 4,
        "Power": 2,
        "Eye": 2,
        "Avoid Ks": 1,
        "BABIP": 1,
        "Contact vL": 3,
        "Gap vL": 4,
        "Power vL": 2,
        "Eye vL": 3,
        "Avoid K vL": 1,
        "BABIP vL": 1,
        "Contact vR": 3,
        "Gap vR": 4,
        "Power vR": 2,
        "Eye vR": 2,
        "Avoid K vR": 1,
        "BABIP vR": 1,
        "GB Hitter Type": 0,
        "FB Hitter Type": 0,
        "BattedBallType": 0,
        "Speed": 6,
        "Steal Rate": 3,
        "Stealing": 6,
        "Baserunning": 8,
        "Sac bunt": 25,
        "Bunt for hit": 44,
        "Stuff": 36,
        "Movement": 94,
        "Control": 93,
        "pHR": 102,
        "pBABIP": 79,
        "Stuff vL": 32,
        "Movement vL": 73,
        "Control vL": 117,
        "pHR vL": 72,
        "pBABIP vL": 76,
        "Stuff vR": 38,
        "Movement vR": 121,
        "Control vR": 77,
        "pHR vR": 140,
        "pBABIP vR": 83,
        "Fastball": 33,
        "Slider": 0,
        "Curveball": 33,
        "Changeup": 0,
        "Cutter": 0,
        "Sinker": 46,
        "Splitter": 0,
        "Forkball": 0,
        "Screwball": 0,
        "Circlechange": 0,
        "Knucklecurve": 0,
        "Knuckleball": 0,
        "Stamina": 25,
        "Hold": 36,
        "GB": 2,
        "Velocity": "88-90",
        "Arm Slot": 3,
        "Height": 193,
        "Infield Range": 35,
        "Infield Error": 20,
        "Infield Arm": 26,
        "DP": 23,
        "CatcherAbil": 0,
        "CatcherFrame": 0,
        "Catcher Arm": 0,
        "OF Range": 1,
        "OF Error": 4,
        "OF Arm": 8,
        "Pos Rating P": 65,
        "Pos Rating C": 0,
        "Pos Rating 1B": 0,
        "Pos Rating 2B": 0,
        "Pos Rating 3B": 0,
        "Pos Rating SS": 0,
        "Pos Rating LF": 0,
        "Pos Rating CF": 0,
        "Pos Rating RF": 0,
        "LearnC": 0,
        "Learn1B": 0,
        "Learn2B": 0,
        "Learn3B": 0,
        "LearnSS": 0,
        "LearnLF": 0,
        "LearnCF": 0,
        "LearnRF": 0,
        "era": 2,
        "tier": 1,
        "MissionValue": 2,
        "limit": 0,
        "owned": 0,
        "brefid": "zuverge01",
        "Buy Order High": 39,
        "Sell Order Low": 149,
        "Last 10 Price": 150,
        "Last 10 Price(VAR)": 0,
        "date": "2025-03-15"        
    }

    const expectedLiveCard = {
        "CardTitle": "MLB 2025 Live RF Jared Young NYM",
        "CardID": 72325,
        "CardValue": 67,
    }

    const historicalLiveCard = {
        "CardTitle": "Snapshot RP George Zuverink BAL 1958",
        "CardID": 70594,
        "CardValue": 69,
        "date": "2025-03-15"
    }

    const script = await ptCardListLoadScript([liveCard,historicalCard],ptCardList);
    const database = new Database(dir + "test.db");

    await database.execute(script);
    const liveCardRecord = await database.get(`select CardID,CardTitle,CardValue from PtCard where CardID = ${expectedLiveCard.CardID}`)
    const historicalCardRecord = await database.get(`select CardID,CardTitle,CardValue,date(date,'auto') date from PtCard where CardID = ${historicalLiveCard.CardID}`)
    
    expect(databaseObjectEqual(liveCardRecord,expectedLiveCard)).toBeTruthy();
    expect(databaseObjectEqual(historicalCardRecord,historicalLiveCard)).toBeTruthy();

})

test('Populate PtCards table with updated live cards', async () => {

    const liveCard = {
        "Card Title": "MLB 2025 Live RF Jared Young NYM",
        "Card ID": 76225,
        "Card Value": 67,
        "Card Type": 1,
        "Card Sub Type": 0,
        "Card Badge": "",
        "Card Series": "",
        "Year": 2025,
        "Peak": "N",
        "Team": "New York Mets",
        "Franchise": "NYM",
        "LastName": "Young",
        "FirstName": "Jared",
        "NickName": "",
        "UniformNumber": 3,
        "DayOB": 9,
        "MonthOB": 7,
        "YearOB": 1995,
        "Bats": 2,
        "Throws": 1,
        "Position": 9,
        "Pitcher Role": 0,
        "Contact": 67,
        "Gap": 86,
        "Power": 77,
        "Eye": 85,
        "Avoid Ks": 66,
        "BABIP": 71,
        "Contact vL": 65,
        "Gap vL": 82,
        "Power vL":74,
        "Eye vL": 79,
        "Avoid K vL": 63,
        "BABIP vL": 70,
        "Contact vR": 69,
        "Gap vR": 87,
        "Power vR": 79,
        "Eye vR": 88,
        "Avoid K vR": 68,
        "BABIP vR": 72,
        "GB Hitter Type": 2,
        "FB Hitter Type": 2,
        "BattedBallType": 0,
        "Speed": 67,
        "Steal Rate": 31,
        "Stealing": 70,
        "Baserunning": 67,
        "Sac bunt": 64,
        "Bunt for hit": 33,
        "Stuff": 1,
        "Movement": 20,
        "Control": 1,
        "pHR": 1,
        "pBABIP": 60,
        "Stuff vL": 1,
        "Movement vL": 20,
        "Control vL": 1,
        "pHR vL": 1,
        "pBABIP vL": 59,
        "Stuff vR": 1,
        "Movement vR": 21,
        "Control vR": 1,
        "pHR vR": 1,
        "pBABIP vR": 62,
        "Fastball": 9,
        "Slider": 0,
        "Curveball": 0,
        "Changeup": 0,
        "Cutter": 0,
        "Sinker": 0,
        "Splitter": 0,
        "Forkball": 0,
        "Screwball": 0,
        "Circlechange": 0,
        "Knucklecurve": 0,
        "Knuckleball": 0,
        "Stamina": 1,
        "Hold": 0,
        "GB": 4,
        "Velocity": "80-83",
        "Arm Slot": 3,
        "Height": 185,
        "Infield Range": 44,
        "Infield Error": 55,
        "Infield Arm": 53,
        "DP": 48,
        "CatcherAbil": 1,
        "CatcherFrame": 1,
        "Catcher Arm": 4,
        "OF Range": 54,
        "OF Error": 60,
        "OF Arm": 51,
        "Pos Rating P": 0,
        "Pos Rating C": 0,
        "Pos Rating 1B": 13,
        "Pos Rating 2B": 0,
        "Pos Rating 3B": 0,
        "Pos Rating SS": 0,
        "Pos Rating LF": 12,
        "Pos Rating CF": 0,
        "Pos Rating RF": 50,
        "LearnC": 0,
        "Learn1B": 1,
        "Learn2B": 1,
        "Learn3B": 1,
        "LearnSS": 1,
        "LearnLF": 1,
        "LearnCF": 1,
        "LearnRF": 1,
        "era": 8,
        "tier": 1,
        "MissionValue": 2,
        "limit": 0,
        "owned": 0,
        "brefid": "youngja02",
        "Buy Order High": 60,
        "Sell Order Low": 195,
        "Last 10 Price": 115,
        "Last 10 Price(VAR)": 0,
        "date": "2025-03-15"
    } as CsvRecord

    const liveCard2 = {
        "Card Title": "MLB 2025 Live RF Jared Young NYM",
        "Card ID": 76225,
        "Card Value": 67,
        "Card Type": 1,
        "Card Sub Type": 0,
        "Card Badge": "",
        "Card Series": "",
        "Year": 2025,
        "Peak": "N",
        "Team": "New York Mets",
        "Franchise": "NYM",
        "LastName": "Young",
        "FirstName": "Jared",
        "NickName": "",
        "UniformNumber": 3,
        "DayOB": 9,
        "MonthOB": 7,
        "YearOB": 1995,
        "Bats": 2,
        "Throws": 1,
        "Position": 9,
        "Pitcher Role": 0,
        "Contact": 67,
        "Gap": 86,
        "Power": 177,
        "Eye": 85,
        "Avoid Ks": 66,
        "BABIP": 71,
        "Contact vL": 65,
        "Gap vL": 82,
        "Power vL":74,
        "Eye vL": 79,
        "Avoid K vL": 63,
        "BABIP vL": 70,
        "Contact vR": 69,
        "Gap vR": 87,
        "Power vR": 79,
        "Eye vR": 88,
        "Avoid K vR": 68,
        "BABIP vR": 72,
        "GB Hitter Type": 2,
        "FB Hitter Type": 2,
        "BattedBallType": 0,
        "Speed": 67,
        "Steal Rate": 31,
        "Stealing": 70,
        "Baserunning": 67,
        "Sac bunt": 64,
        "Bunt for hit": 33,
        "Stuff": 1,
        "Movement": 20,
        "Control": 1,
        "pHR": 1,
        "pBABIP": 60,
        "Stuff vL": 1,
        "Movement vL": 20,
        "Control vL": 1,
        "pHR vL": 1,
        "pBABIP vL": 59,
        "Stuff vR": 1,
        "Movement vR": 21,
        "Control vR": 1,
        "pHR vR": 1,
        "pBABIP vR": 62,
        "Fastball": 9,
        "Slider": 0,
        "Curveball": 0,
        "Changeup": 0,
        "Cutter": 0,
        "Sinker": 0,
        "Splitter": 0,
        "Forkball": 0,
        "Screwball": 0,
        "Circlechange": 0,
        "Knucklecurve": 0,
        "Knuckleball": 0,
        "Stamina": 1,
        "Hold": 0,
        "GB": 4,
        "Velocity": "80-83",
        "Arm Slot": 3,
        "Height": 185,
        "Infield Range": 44,
        "Infield Error": 55,
        "Infield Arm": 53,
        "DP": 48,
        "CatcherAbil": 1,
        "CatcherFrame": 1,
        "Catcher Arm": 4,
        "OF Range": 54,
        "OF Error": 60,
        "OF Arm": 51,
        "Pos Rating P": 0,
        "Pos Rating C": 0,
        "Pos Rating 1B": 13,
        "Pos Rating 2B": 0,
        "Pos Rating 3B": 0,
        "Pos Rating SS": 0,
        "Pos Rating LF": 12,
        "Pos Rating CF": 0,
        "Pos Rating RF": 50,
        "LearnC": 0,
        "Learn1B": 1,
        "Learn2B": 1,
        "Learn3B": 1,
        "LearnSS": 1,
        "LearnLF": 1,
        "LearnCF": 1,
        "LearnRF": 1,
        "era": 8,
        "tier": 1,
        "MissionValue": 2,
        "limit": 0,
        "owned": 0,
        "brefid": "youngja02",
        "Buy Order High": 60,
        "Sell Order Low": 195,
        "Last 10 Price": 115,
        "Last 10 Price(VAR)": 0,
        "date": "2025-03-15"
    }

    const database = new Database(dir + "test.db");

    database.execute("insert into LiveUpdate (EffectiveDate) values ('2025-04-01')");

    const script1 = await ptCardListLoadScript([liveCard],ptCardList);
    await database.execute(script1);

    database.execute("insert into LiveUpdate (EffectiveDate) values ('2025-05-01')");

    const script2 = await ptCardListLoadScript([liveCard2],ptCardList);
    await database.execute(script2);

    const liveCards = await database.getAll(`select CardID,CardTitle,CardValue from PtCard where CardID = ${liveCard.CardID}`)

    expect(liveCards.length).toBe(2);
    expect(liveCards[0].LiveUpdateID !== liveCards[1].LiveUpdateID);
    
})
