export interface CsvRecord {
    [index:string]: string|number,
}

export interface DatabaseRecord {
    [index:string]: string|number,
}

export interface CsvDataColumn {
    nameInSource: string,
    databaseColumnName: string,
    type: string,
}

export interface DatatableColumn {
    name: string,
    type: string,
    isNullable: boolean,
}

export interface Constraint {
    type: "UNIQUE"|"INDEX"
    name: string,
    fields: string[],
}

export interface DatatableModel {
    columns: DatatableColumn[],
    primaryKey?: string,
    constraints?: Constraint[],
}

export interface PitchingStats {
    PtCardID: number,
    G: number,
    GS: number,
    W: number,
    L: number,
    "WIN%": number,
    SVO: number,
    SV: number,
    "SV%": number,
    BS: number,
    "BS%": number,
    HLD: number,
    SD: number,
    MD: number,
    IP: number,
    BF: number,
    AB: number,
    HA: number,
    "1B": number,
    "2B": number,
    "3B": number,
    HR: number,
    TB: number,
    R: number,
    ER: number,
    BB: number,
    IBB: number,
    K: number,
    HP: number,
    ERA: number,
    AVG: number,
    OBP: number,
    SLG: number,
    OPS: number,
    BABIP: number,
    WHIP: number,
    "BRA/9": number,
    "HR/9": number,
    "H/9": number,
    "BB/9": number,
    "K/9": number,
    "K/BB": number,
    "K%": number,
    "BB%": number,
    "K%-BB%": number,
    SH: number,
    SF: number,
    WP: number,
    BK: number,
    CI: number,
    DP: number,
    RA: number,
    GF: number,
    IR: number,
    IRS: number,
    "IRS%": number,
    "LOB%": number,
    pLi: number,
    "GF%": number,
    QS: number,
    "QS%": number,
    CG: number,
    "CG%": number,
    SHO: number,
    PPG: number,
    RS: number,
    RSG: number,
    PI: number,
    GB: number,
    FB: number,
    "GO%": number,
    SB: number,
    CS: number,
    "ERA+": number,
    FIP: number,
    "FIP-": number,
    WPA: number,
    WAR: number,
    rWAR: number,
    SIERA: number,
    Outs: number,
}